apiVersion: v1
kind: Pod
metadata:
  name: busy-pod
  labels:
    owner: fivezjd
    env: demo
    region: north
    tier: back
spec:
  containers:
    - image: busybox
      name: busy
      imagePullPolicy: IfNotPresent
      env:
        - name: os
          value: "ubuntu"
        - name: debug
          value: "on"
      command:
        - /bin/echo
      args:
        - "$(os),$(debug)"

